name: Build .NET Core
on:
  push:
    tags: 
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Process Version from Tag
      id: version
      uses: ncipollo/semantic-version-action@v1

    - name: Write Version to Text File
      env:
        BUILD_VERSION: ${{ steps.version.outputs.tag }}
      run: |
        echo "source: ${Env:GITHUB_REPOSITORY}" > "${Env:GITHUB_WORKSPACE}\VERSION.md"
        echo "version: ${Env:BUILD_VERSION}" >> "${Env:GITHUB_WORKSPACE}\VERSION.md"
        echo "commit: ${Env:GITHUB_SHA}" >> "${Env:GITHUB_WORKSPACE}\VERSION.md"
        echo "date: $((Get-Date -format r).ToString())" >> "${Env:GITHUB_WORKSPACE}\VERSION.md"

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Build with dotnet
      env:
        BUILD_VERSION: ${{ steps.version.outputs.tag }}
      run: |
        $VERSION = ${Env:BUILD_VERSION}.Substring(1)
        $COMMIT_HASH = ${Env:GITHUB_SHA}.Substring(0, 7)
        $INFORMATIONAL_VERSION="${VERSION}+${$COMMIT_HASH}"
        dotnet build --configuration Release /p:VersionPrefix=${VERSION} /p:InformationalVersion=${INFORMATIONAL_VERSION}

    - name: Package Artifacts
      env:
        BUILD_VERSION: ${{ steps.version.outputs.tag }}
      run: |
        $BuildName = (gci *.sln)[0].BaseName
        $BuildDir = ${BuildName} + ".UI\bin\Release\netcoreapp3.1\"
        7z a "${BuildName}-${Env:BUILD_VERSION}.zip" "${Env:GITHUB_WORKSPACE}\${BuildDir}" "-xr!*.pdb" "-mx=7"
        # Adding folders with 7z uses the last folder name in $BuildDir (e.g., netcoreapp3.1), so it needs to be renamed
        $FolderToRename = Split-Path ${BuildDir} -Leaf  
        7z rn "${BuildName}-${Env:BUILD_VERSION}.zip" "${FolderToRename}" "${BuildName}"

    - name: Publish to GitHub Releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          *.zip
